import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Instagram, MapPin } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa6";
import { Button } from "@/components/ui/button";
import { BARBER_CHAT, INSTAGRAM, MAPS, QUOTE, SiteLayout, WHATSAPP_DISPLAY } from "@/components/site-layout";

export const Route = createFileRoute("/contato")({ head: () => ({ meta: [
  { title: "Contato e Localização | Lucas Pedroso Tattoo & Barber" },
  { name: "description", content: "Converse pelo WhatsApp sobre tatuagem ou barbearia e encontre a Franqueza na R. Santa Maria, 63, Vila Hortência, Sorocaba." },
  { property: "og:title", content: "Contato e Localização | Lucas Pedroso Tattoo & Barber" },
  { property: "og:description", content: "WhatsApp e endereço da Franqueza Barbearia em Sorocaba." },
  { property: "og:type", content: "website" },
  { name: "twitter:card", content: "summary_large_image" },
] }), component: Contato });

function Contato() { return <SiteLayout><main><section className="page-shell grid gap-12 pb-16 pt-16 md:grid-cols-[1fr_.75fr] md:gap-20 md:pb-28 md:pt-28"><div><span className="micro-label text-muted-foreground">Contato / Orçamento</span><h1 className="display-serif mt-7 text-[clamp(66px,9vw,132px)]">Vamos criar<br/><em>algo juntos?</em></h1><div className="mt-9 grid max-w-lg gap-4 sm:grid-cols-2"><div className="border border-border p-6"><span className="micro-label text-muted-foreground">Tatuagem</span><p className="mt-3 text-sm leading-7 text-muted-foreground">Envie suas referências, a região do corpo e o tamanho aproximado.</p></div><div className="border border-border p-6"><span className="micro-label text-muted-foreground">Barbearia</span><p className="mt-3 text-sm leading-7 text-muted-foreground">Conte como você gosta de usar o cabelo no dia a dia.</p></div></div><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="ochre" size="lg" className="h-14 rounded-none px-6 text-xs font-bold uppercase tracking-[.12em]"><a href={QUOTE} target="_blank" rel="noopener noreferrer">Orçamento tattoo <ArrowUpRight size={16}/></a></Button><Button asChild variant="outline" size="lg" className="h-14 rounded-none px-6 text-xs font-bold uppercase tracking-[.12em]"><a href={BARBER_CHAT} target="_blank" rel="noopener noreferrer">Agendar corte <ArrowUpRight size={16}/></a></Button></div><p className="mt-4 text-xs text-muted-foreground">Você será direcionado ao WhatsApp.</p></div><div className="flex flex-col justify-center border-t border-border md:border-l md:border-t-0 md:pl-16"><div className="border-b border-border py-8"><FaWhatsapp size={24} className="text-whatsapp"/><span className="micro-label mt-6 block text-muted-foreground">WhatsApp</span><a href={QUOTE} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-3 font-display text-3xl text-whatsapp hover:underline">{WHATSAPP_DISPLAY} <ArrowUpRight size={17}/></a></div><div className="border-b border-border py-8"><Instagram size={24} strokeWidth={1.3}/><span className="micro-label mt-6 block text-muted-foreground">Instagram</span><a href={INSTAGRAM} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-3 font-display text-3xl hover:underline">@lucaspedrosoink <ArrowUpRight size={17}/></a></div><div className="py-8"><MapPin size={24} strokeWidth={1.3}/><span className="micro-label mt-6 block text-muted-foreground">Franqueza Studio</span><p className="mt-3 font-display text-3xl">Vila Hortência, Sorocaba</p><p className="mt-3 text-sm leading-7 text-muted-foreground">R. Santa Maria, 63 · Vila Hortência<br/>Sorocaba - SP, 18020-216</p><Button asChild variant="outline" className="mt-6 h-11 rounded-none px-5 text-xs font-bold uppercase tracking-[.12em]"><a href={MAPS} target="_blank" rel="noopener noreferrer">Abrir no Google Maps <ArrowUpRight size={16}/></a></Button></div></div></section></main></SiteLayout>; }
